# -*- coding: utf-8 -*-
"""Checking_Data_Augmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SNeesYU_5gXlG6zdh0lNl_4sEOM4fLno
"""

import tensorflow as tf

train_path = "/content/drive/My Drive/Chest X-ray Image/train/Covid_19"

from tensorflow.keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale = 1.0/255,
                                   rotation_range = 5,
                                   width_shift_range = 0.1,
                                   height_shift_range = 0.05,
                                   shear_range = 0.1,
                                   zoom_range = 0.15,
                                   horizontal_flip = True,
                                   fill_mode = "reflect")

import random, os
chosen_image = random.choice(os.listdir(train_path))
image_path = "/content/drive/My Drive/Chest X-ray Image/train/Covid_19/" + chosen_image

assert os.path.isfile(image_path)

import numpy as np
import matplotlib.pyplot as plt
import cv2
img = np.expand_dims(cv2.imread(image_path),0)
plt.imshow(img[0])

def plotImages(images_arr):
  fig, axes = plt.subplots(2,5, figsize = (224,224))
  axes = axes.flatten()
  for img,ax in zip(images_arr, axes):
    ax.imshow(img)
    ax.axis("off")
  plt.tight_layout()
  plt.show()

aug_iter = train_datagen.flow(img)

aug_img = [next(aug_iter)[0] for i in range (10)]
plotImages(aug_img)





